# This is a basic workflow to help you get started with Actions
#this is just a sample checkin
name: Trigger Azure Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the feature/docker branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: calling azure pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
    # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
         azure-devops-project-url: https://dev.azure.com/MachineCDN/KORE_WB
    # Name of the Azure Pipline to be triggered
         azure-pipeline-name: MachineCDN.wirelessbackup-frontend
    # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
         azure-devops-token: lutliyfbs3g52worv3pukvphcc64vt3fadzfoi3sqzgv2vt2e5da
